### ISSUE TITLE
codesnippet or syntaxhighlight in CKEditor

### ISSUE THREAD

**Issue by annak1n** [ophian/styx#1]
Hi How i can add codesnippet or syntaxhighlight in CKEditor ?

**Comment by ophian** [comment]
May it be that you're barking the wrong tree? This is **Serendipity Styx**. A PHP weblog system, since 2002/2003 .
I do support CKE with codesnippet and syntaxhighlight by plugin.
But this is NOT
> serendipity (_whyever they stole our name.._)
> Forked from Robinyo/serendipity
> Serendipity is an open source Customer Engagement Platform
