### ISSUE TITLE
Themes Timeline on handy!

### ISSUE THREAD

**Issue by ElfenTroll** [ophian/styx#21]
Hi,

I use the current version of the Themes Timeline. I just noticed that the site name at the top on mobile doesn't wrap in the mobile view if it's very long. Can someone tell me where I can adjust this. Which file do I have to change for how .... Would be very important to me!

And sorry, I'm a total layman and therefore not experienced in these things!

Ich nutze das Themes Timeline in der aktuellen Version. Mir ist gerade aufgefallen, dass der Name der Website oben auf dem Handy nicht in der mobilen Ansicht umgebrochen wird, wenn er sehr lang ist. Kann eventuell mir da jemand kurz beschreiben wo ich das anpassen kann. Welche Datei muss ich dafür wie verändern .... Wäre mir sehr wichtig!

Und sorry, ich bin totaler Laie und daher nicht erfahren in diesen Sachen!

Michael E.

![umbruch](https://user-images.githubusercontent.com/101506660/158068566-8f19f739-f42c-481b-b709-288a5eb7f018.jpg)

**Comment by ophian** [comment]
Familiarize yourself with the concept of a child theme that can use - or at all - a user.css file. This is - if present - automatically included below the style.csss file and can thus overwrite everything in it.
(See info (button) text of Pure themes under: Create your own theme)

Mache dich mal mit dem Konzept eines Child-Themes bekannt, dass - bzw überhaupt - eine user.css Datei benutzen kann.Diese wird - wenn vorhanden - automatisch unterhalb der style.csss Datei eingebunden und kann somit alles darin vorhandene überschreiben.
(Siehe info (button) Text des Pure themes unter: Eigenes Theme erstellen)

darin
```css
.container .navbar-brand h1 {
  white-space: break-spaces;
}
```

**Comment by ElfenTroll** [comment]
Okay, da muss ich mich echt erst in Ruhe mit beschäftigen .... Aber in welcher vorhandenen Themes Datei kann ich das den jetzt direkt einfügen, so dass es erst einmal sauber funktioniert!?

Okay, I really have to deal with that in peace first.... But in which existing themes file can I insert it directly, so that it works properly first of all!?

**Comment by ophian** [comment]
...in eine user.css Dateim die du in das timeline theme legst, wenn du kein eigenes child theme benutzt.

**Comment by ElfenTroll** [comment]
Hm, irgendwie will das nicht funktionieren, Ich habe eine leere user.css erstellt und da den Code eingefügt und die Datei dann in den Timeline Ordner gelegt. Tut sich aber nichts! Wie der Dateiinhalt den insgesamt aussehen und muss ich diese Datei noch irgendwo einbinden?? Das mit dem Child-Themes habe ich noch nicht ganz verstanden, da muss ich mich erst mit auseinandersetzen!

Hm, somehow that doesn't want to work. I created an empty user.css and inserted the code there and then put the file in the timeline folder. But nothing happens! What does the file content look like overall and do I have to integrate this file somewhere? I still don't quite understand the child themes, I have to deal with that first!

**Comment by ophian** [comment]
Doch. ist da. Ganz unten
```css
/* auto include templates/timeline/user.css */

.container .navbar-brand h1 {
  white-space: break-spaces;
}
```
Liegt wahrscheinlich am Brower cache. [Ctrl] + [r] + [F5]

**Comment by ElfenTroll** [comment]
Ah, sehe gerade es betrifft offenbar nur den Opera - Browser auf dem Handy (Android) ... im IE scheint es zu funktionieren?!

Nun gut, ich werde noch ein bisschen fummeln .... 

Eine kurze Frage noch: Welches wäre die optimale Bildbreite für den Header im Themes Timeline, so dass es möglichst überall gut angezeigt wird?

Ist es eigentlich okay solche "simplen" Fragen hier zu stellen, oder gibt es dafür bei Dir ein anderes Forum?

**Comment by ophian** [comment]
Ich weiß es nicht. Du meinst das header Bild?
Vielleicht 1200px für einen maximalen Desktop?!? Wer es größer betreibt ist selbst Schuld.
Clean Blog und Timeline sind von Don Chambers. Ich habe sie nur für Styx repariert.
Wenn ich kann und das nicht übermäßig ausgenuzt wird helfe ich gerne und solange es sich nicht um Bugs handelt ist man im https://github.com/ophian/styx/discussions Discussion "Forum" vielleicht besser aufgehoben.

IE ist tot!!!! Aber sowas von!

**Comment by ElfenTroll** [comment]
Hallo, danke für Deine Hilfe ... Gut, werde dann die Themen trennen und das andere Forum für "Nichtbugs" nutzen.Das Themes Timeline finde ich echt sehr gut und ebenso das es toll optimiert wurde von Dir ... Wäre schön wenn das neben Deiner s9y zukünftig auch weiter noch gepflegt würde. Ich habe übrigens zuvor das Original s9y getestet und mich dann für Deine Version entschieden, weil bei Dir offenbar wirklich mehr passiert. Das Original wird ja kaum noch gepflegt oder angepasst, was Schade ist, und im Forum gekonnt man auch nicht viel Hilfe. Ich finde s9y ist eine absolut superspannende Geschichte und bin deswegen extra von WP weg gegangen, welches mir zu pflegeintensiv und Fehleranfällig wurde. Hoffe das es bei Dir noch lange so weitergeht und das System auch viele Jahre noch gepflegt wird. Sprich, super Job, super CMS und tolle Arbeit! Ich werde ein Fan, das weiß ich jetzt schon ... :-) :-) Gruß Michael E. --------------------------------------------------Respice post te, hominem te esse memento! (Sueton "Iulius" 51)Contact via messenger "Threema"; ID: KV2KKHAF ... https://threema.ch/deInfo / Note: Diese E-Mail ist nur für den angegebenen Empfänger bestimmt; This e-mail is intended only for the designated recipient.Security: E-mail protected and checked by "Sophos Intercept X", "McAfee Total Protection" or "Microsoft Defender".Von: Ian ***@***.***>Gesendet: Sonntag, 13. März 2022, 19:22An: ophian/styx ***@***.***>Cc: ElfenTroll ***@***.***>; Author ***@***.***>Betreff: Re: [ophian/styx] Themes Timeline on handy! (Issue #21)Ich weiß es nicht. Du meinst das header Bild?

Vielleicht 1200px für einen maximalen Desktop?!? Wer es größer betreibt ist selbst Schuld.

Clean Blog und Timeline sind von Don Chambers. Ich habe sie nur für Styx repariert.

Wenn ich kann und das nicht übermäßig ausgenuzt wird helfe ich gerne und solange es sich nicht um Bugs handelt ist man im https://github.com/ophian/styx/discussions Discussion "Forum" vielleicht besser aufgehoben.IE ist tot!!!! Aber sowas von!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>Von: Ian ***@***.***>Gesendet: Sonntag, 13. März 2022, 19:22An: ophian/styx ***@***.***>Cc: ElfenTroll ***@***.***>; Author ***@***.***>Betreff: Re: [ophian/styx] Themes Timeline on handy! (Issue #21)Ich weiß es nicht. Du meinst das header Bild?

Vielleicht 1200px für einen maximalen Desktop?!? Wer es größer betreibt ist selbst Schuld.

Clean Blog und Timeline sind von Don Chambers. Ich habe sie nur für Styx repariert.

Wenn ich kann und das nicht übermäßig ausgenuzt wird helfe ich gerne und solange es sich nicht um Bugs handelt ist man im https://github.com/ophian/styx/discussions Discussion "Forum" vielleicht besser aufgehoben.IE ist tot!!!! Aber sowas von!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>Von: Ian ***@***.***>Gesendet: Sonntag, 13. März 2022, 19:22An: ophian/styx ***@***.***>Cc: ElfenTroll ***@***.***>; Author ***@***.***>Betreff: Re: [ophian/styx] Themes Timeline on handy! (Issue #21)

Ich weiß es nicht. Du meinst das header Bild?

Vielleicht 1200px für einen maximalen Desktop?!? Wer es größer betreibt ist selbst Schuld.

Clean Blog und Timeline sind von Don Chambers. Ich habe sie nur für Styx repariert.

Wenn ich kann und das nicht übermäßig ausgenuzt wird helfe ich gerne und solange es sich nicht um Bugs handelt ist man im https://github.com/ophian/styx/discussions Discussion "Forum" vielleicht besser aufgehoben.

IE ist tot!!!! Aber sowas von!

**Comment by ophian** [comment]
ich habe da mal augeräumt...und deineb mail kram entfernt Du hast gesehenm dass ich noch so einiges korrigiert hatte im letzten Post?
