### ISSUE TITLE
Error Plugin "Statische Seiten" ...

### ISSUE THREAD

**Issue by ElfenTroll** [ophian/styx#25]
Hallo,

nach Installation des Plugins "Statische Seiten" funktioniert die Website nicht mehr, es kommt nur noch eine 500er Fehlermeldung!

![Ashampoo_Snap_Dienstag, 15  März 2022_16h13m29s](https://user-images.githubusercontent.com/101506660/158413376-ec639019-53b3-4475-8f02-c4bb4e80dea8.png)

**Comment by ElfenTroll** [comment]
Ich hatte es schlicht installiert und direkt danach trat der Fehler sofort auf, die Seite war weg ... Als ich es dann deinstallierte funktionierte die Seite wieder.

Gerne richte ich übrigens für Dich einen Adminzugang ein, damit Du es selbst testen kannst. Ich brauche nur eine Mailadresse an welche ich Dir die Daten schicken kann ... Die kann ich ja schlecht hier öffentlich einstellen!

**Comment by ophian** [comment]
die ich hier ebenso wenig öffentlich hinschreiben möchte....
Wenn die Seite weg ist ist es meist ein fatal error, der dann in den Server logs zu finden wäre. Hast du darauf Zugriff?

**Comment by ElfenTroll** [comment]
Siehe bitte auch neue Meldung zu "Benutzer anlegen", da gibt es Zugangsdaten für Dich ... Bitte einloggen und Passwort ändern!

**Comment by ophian** [comment]
Ok. Ich habe gerade die 6.48 released. (wenn du nicht warten willst musst du einmal das Spartacus Plugin bzw dessen config) neu abspeichern.
Das war ein uraltes Unterfangen aus den uralten Tagen wo das Plugin sich noch entwickelte und alte Einträge umorientiert werden sollten, was auch nicht wirklich einen Sinn machte. Anstelle wie früher einfach weiterzumachen als ob nichts wäre wird dies nun dankenswerterweise angezeigt.
Ich habe diesen alten Teil der staticpage DB Installatiobsroutine jetzt einfach gelöscht da es überhaupt keinen Sinn machte.
Wahrscheinlich sind deine Einträge in der `styx_config` Tabelle und den staticpage Tabellen (sind deren vier)  nur unvollständig aufgeschlagen. Ich habe keine Reparatur eingefügt, da ich glaube, dass das mit dem Plugin update selbständig passiert. Wir sollten also nach dem Update noch einmal vergleichen.

**Comment by ElfenTroll** [comment]
Okay, dann warte ich auf das Update ...

**Comment by ElfenTroll** [comment]
Und zur Not kann ich auch noch einmal neu installieren ... Noch ist ja alles im Fluss! :-) :-)

**Comment by ophian** [comment]
Kann das abgeschlossen werden?

**Comment by ElfenTroll** [comment]
Hallo Ian,ich bin noch im Krankenhaus und komme erst Morgen nach Hause!! Danach werde ich mich dann wieder mit dem System beschäftigen. Heißt, ich konnte es noch nicht testen .. Es gibt ja jetzt 3.8.1 und ich werde es daher wohl erneut komplett neu einspielen, war ja noch nicht so weit. Melde mich dann ... Gruß Michael E. --------------------------------------------------Respice post te, hominem te esse memento! (Sueton "Iulius" 51)"Threema" Messenger contact under the ID: KV2KKHAF ... or directly via this web link:https://threema.bloggernotizen.deInfo / Note: Diese E-Mail ist nur für den angegebenen Empfänger bestimmt; This e-mail is intended only for the designated recipient.Security: E-mail protected and checked by "Sophos Intercept X", "McAfee Total Protection" or "Microsoft Defender".Von: Ian ***@***.***>Gesendet: Sonntag, 27. März 2022, 14:38An: ophian/styx ***@***.***>Cc: Michael Erich Pilarczyk ***@***.***>; Author ***@***.***>Betreff: Re: [ophian/styx] Error Plugin "Statische Seiten" ... (Issue #25)
Kann das abgeschlossen werden?

**Comment by ophian** [comment]
close for now
