### ISSUE TITLE
Error Plugin "Archive" ...

### ISSUE THREAD

**Issue by ElfenTroll** [ophian/styx#26]
Hallo,

wenn man in der Archiv - Übersicht unter "Ältere" oder "Das Neuste" (Seitenleiste) auf das angezeigte Monatsfeld (Grünes Feld) klickt passiert nichts bzw. werden keine Einträge angezeigt. Verwendetes Themes "Timeline" ...  Meine Website ist übrigens zu finden unter www.mindennotizen.de ... Dort findet die Einrichtung statt!

![Ashampoo_Snap_Dienstag, 15 März 2022_16h23m32s](https://user-images.githubusercontent.com/101506660/158413937-942efffd-6492-46ad-9d19-b6a479b26d5c.png)

**Comment by ophian** [comment]
Das beruht auf javascript errors. 
u.a. Uncaught TypeError: Bootstrap's dropdowns require Popper (https://popper.js.org/)
was hast du angeschaltet das bootstrap auf popper besteht?

**Comment by ElfenTroll** [comment]
Hm, wo kann ich da was an- oder ausschalten??? Oder ist das eine Serversache, dann müsse ich den Support des Providers kontaktieren!?

**Comment by ophian** [comment]
setzte das popper cdn in die leere Zeile

**Comment by ElfenTroll** [comment]
Okay, funktioniert ... Schließe ich dann erst einmal! Danke ...
