### ISSUE TITLE
Error "Neuen Benutzer anlegen" ...

### ISSUE THREAD

**Issue by ElfenTroll** [ophian/styx#27]
Hallo Ian,

ich habe gerade einen Adminzugang angelegt für Dich und dabei trat folgender Fehler auf (Siehe Bild) .... Bitte mit folgenden Daten anmelde und dann sofort bitte Passwort usw. ändern: Ian und ***** .... Der Zugang funktioniert aber trotz Fehlermeldung!

![Ashampoo_Snap_Dienstag, 15  März 2022_17h1m36s](https://user-images.githubusercontent.com/101506660/158420227-de8939ac-c7c9-4f53-95a0-2e414f2f020c.png)

**Comment by ophian** [comment]
ok, ist geschehen. Danke.
Für die anderen Sachen wie staticpage brauche ich noch ein wenig. So viel dazu, diese neue mysqli_sql_exception ist großartig, zeigt sie doch gnadenlost uralte Unstimmigkeiten auf. Leider bist du gerade derjenige, den es erwischt! Sorry dafür.

**Comment by ophian** [comment]
fixed
