### ISSUE TITLE
SQL server going away when saying personal settings

### ISSUE THREAD

**Issue by hbarel** [ophian/styx#34]
When saving personal settings, PHP crashes with the error:

`PHP Fatal error:  Uncaught mysqli_sql_exception: MySQL server has gone away in /var/www/html/include/db/mysqli.inc.php:76`

This is probably not critical, because changes _are_ saved.

**Comment by hbarel** [comment]
You are most likely right. It sounds like a server issue, and probably just for the staging machine.
Please close this issue.

**Comment by ophian** [comment]
-btw., which maria/mysql server are you using and in which version?

**Comment by hbarel** [comment]
> -btw., which maria/mysql server are you using and in which version?

10.5.15-MariaDB-0+deb11u1

But it did not reproduce on another machine, so it's certainly something local. Thanks!
