### ISSUE TITLE
Error because of .htaccess

### ISSUE THREAD

**Issue by halojoy** [ophian/styx#41]
In .htaccess this will not work:
**Deny from all**

Now Should be:
**Require all denied**

The result was an internal server error after the install.

**Comment by ophian** [comment]
You are right. But where did you get that?
Which theme or plugin is in use? Since I can't remember the Serendipity generated .htaccess has anything like this.

**Comment by ophian** [comment]
@halojoy
Uihhh ... you certainly mean

```htacess
<Files *.tpl.php>
    deny from all
</Files>

<Files *.tpl>
    deny from all
</Files>

<Files *.sql>
    deny from all
</Files>

<Files *.inc.php>
    deny from all
</Files>

<Files *.db>
    deny from all
</Files>
```

Its very strange I did not get this in all my years...

Could you try and replace each 
```
    deny from all
```
line with this
```
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
```

and see how this works, please.

**Comment by halojoy** [comment]
The apache  I have is 2.4.52
I have loaded module authz_core_module.
It looks as 'Deny from all' no longer is supported.

I will see if I will use your suggested workaround.
If so I will post back.

**Comment by ophian** [comment]
I think we can reduce that to Apache 2.3 syntax.
Apache 2.2 is gone.

Thanks again!

**Comment by halojoy** [comment]
Now I have done like you said.
And this works well. No internal server error.

<Files *.tpl.php>
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
</Files>

**Comment by ophian** [comment]
@halojoy 
May I ask how you got (or detailly produced) this internal server error after the install? I never had this with Apache 2.4 versions and Serendipity, though I know there were issues on web servers generally when it came to migrations to 2.3+ in the very past.
So maybe this is just an issue with some (default) `httpd.conf` settings?

**Comment by halojoy** [comment]
500 Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

So, ''Deny from all' is what generates this error in Apache.
The install was without error.
After this when I clicked to go to website, then was this error.

I tested now with the old .htaccess. Then was the same error.
It is obvious Deny from all generates this error.

But if we have the IF you show me in your previous post.
We can have both REQUIRED and DENY.
This is a good workaround.

Maybe this error is because I use **auth_core_mod**

**Comment by halojoy** [comment]
Loadmodule mod_authz_core is default in Apache 2.4.52.
Probably in all Apache 2.4.
I am almost sure of this.

**Comment by ophian** [comment]
@halojoy Could you please do me a favour and test having both in the .htaccess file without the mod:auth ifs, please?
Then we could add this as the default for a while for all those that still run presumably local old apache versions.
Thanks

Like this:

```conf
 <Files *.tpl.php>
    deny from all
    Require all denied
 </Files>
 
 <Files *.tpl>
    deny from all
    Require all denied
 </Files>
 
 <Files *.sql>
    deny from all
    Require all denied
 </Files>
 
 <Files *.inc.php>
    deny from all
    Require all denied
 </Files>
 
 <Files *.db>
    deny from all
    Require all denied
 </Files>
```

**Comment by ophian** [comment]
> Loadmodule mod_authz_core is default in Apache 2.4.52.
> Probably in all Apache 2.4.
> I am almost sure of this.

Yes. See:
https://en.wikipedia.org/wiki/List_of_Apache_modules

**Comment by halojoy** [comment]
Yes, mod_access_compat is for this. Or it was in times before.
Now in Apache 2.4 the mod_access_compat is not loaded by default.

Serendipity has only Deny Allow in the htaccess!
But you now know much better :)
