### ISSUE TITLE
Add Media. Spaces in the image name

### ISSUE THREAD

**Issue by halojoy** [ophian/styx#43]
I got some error when inserting image through Add Media.
The link in entry was corrupted, if the image name has some space in it.

**Comment by ophian** [comment]
That should not happen. 
Example: Spaghetti alla Puttanesca.jpg will end up as Spaghetti_alla_Puttanesca.jpg including all variations.
It is not allowed to have spaces in file names which is a windows specifica. That is why all spaces will turn into _ underscores on upload to the MediaLibrary.
